/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as DIdRouteImport } from './routes/d.$id'
import { Route as NSlugRouteImport } from './routes/n.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const DIdRoute = DIdRouteImport.update({
  id: '/d/$id',
  path: '/d/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/methodology': typeof MethodologyRoute
  '/d/$id': typeof DIdRoute
  '/n/$slug': typeof NSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/methodology': typeof MethodologyRoute
  '/d/$id': typeof DIdRoute
  '/n/$slug': typeof NSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/methodology': typeof MethodologyRoute
  '/d/$id': typeof DIdRoute
  '/n/$slug': typeof NSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/changelog' | '/methodology' | '/d/$id' | '/n/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/changelog' | '/methodology' | '/d/$id' | '/n/$slug'
  id: '__root__' | '/' | '/changelog' | '/methodology' | '/d/$id' | '/n/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  MethodologyRoute: typeof MethodologyRoute
  DIdRoute: typeof DIdRoute
  NSlugRoute: typeof NSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$id': {
      id: '/d/$id'
      path: '/d/$id'
      fullPath: '/d/$id'
      preLoaderRoute: typeof DIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  MethodologyRoute: MethodologyRoute,
  DIdRoute: DIdRoute,
  NSlugRoute: NSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
