// Facts per slug that are not in census.yaml. Addresses come from PRD Appendix A and the
// prototype's profiles; every one is verified:false until reproduced on Blockscout.
export const RESEARCHER = "harsharn10";
export const LINK_KIND_TO_SOURCE_KIND = { site: "official-site", app: "official-site", docs: "docs", whitepaper: "whitepaper", x: "social", github: "repository", telegram: "social", discord: "social", other: "other" };

export const SEED = {
  pons: { symbol: null, dependencies: ["uniswap", "usdg", "stock-tokens"],
    summary: "Native launchpad on Robinhood Chain: tokens launch on a V2 bonding curve and graduate to Uniswap v4; quote assets include ETH, USDG and Stock Tokens.",
    addresses: [ { label: "V2 curve / factory", address: "not-verified", role: "factory" } ],
    missing: ["Deployment map (curve, factory, graduation router) not yet reproduced on Blockscout", "Privileged roles over the curve and graduation path unknown", "Audit status unknown", "Team identity and repository not yet located"] },
  mancer: { symbol: "MANCER", dependencies: ["uniswap"],
    summary: "Native DEX aggregator with resting orders; Chain Mancers NFT and $MANCER token; a Shield product is announced.",
    addresses: [ { label: "Aggregator router", address: "not-verified", role: "router" }, { label: "$MANCER token", address: "not-verified", role: "token" } ],
    missing: ["Router and token addresses not yet located", "Non-custodial order claim not verified against contracts", "NFT fee-claim mechanics unverified", "Shield: announced only — no deployment evidence reviewed"] },
  "artificial-inu": { symbol: "AI", dependencies: ["stock-tokens", "uniswap"],
    summary: "Flagship LONG launch: $AI paired to tokenized NVDA on Uniswap, with a community vault.",
    addresses: [ { label: "$AI token", address: "0x2E8c31162b855A2ffa90F6F8634643Ad6F111e18", role: "token" } ],
    missing: ["Token address from PRD Appendix A not yet reproduced on Blockscout", "Community vault contract and its controller unknown", "Fee routing and pair mechanics unverified", "NVDA Stock Token dependency card incomplete"] },
  longshot: { symbol: null, dependencies: ["hyperliquid"],
    summary: "Launch and fee-routing protocol on Robinhood Chain; fees split into a fixed Hyperliquid perp position, holder rewards and the protocol.",
    addresses: [ { label: "RH Chain token", address: "0x8701E2C87ade58325601f4F9bf37ADF46Cb75745", role: "token" } ],
    missing: ["Token address from PRD Appendix A not yet reproduced on Blockscout", "Who controls the Hyperliquid position and how funds cross venues", "Fee-split contract and admin powers unknown", "Audit status unknown"] },
  long: { symbol: null, dependencies: ["stock-tokens"],
    summary: "Stock-paired launchpad (Factory + Airlock) that made stock-paired tokens possible on Robinhood Chain; $AI launched here.",
    addresses: [ { label: "Factory (PRD lists 0x9c88…0845, truncated)", address: "not-verified", role: "factory" }, { label: "Factory (PRD lists 0x22e9…eeED, truncated)", address: "not-verified", role: "factory" } ],
    missing: ["Full factory addresses (PRD Appendix A is truncated)", "Airlock controls and who can release", "Launch fee flows", "Audit status unknown"] },
  stonkbroker: { symbol: null, dependencies: ["stock-tokens"],
    summary: "ERC-6551 token-bound NFT on Robinhood Chain that can hold Stock Tokens; a native cultural and product layer.",
    addresses: [ { label: "NFT collection", address: "not-verified", role: "token" } ],
    missing: ["Official site or account not yet located", "Collection and registry addresses unknown", "Who can move assets out of a token-bound account", "Lifecycle stage not independently verified"] },
  index: { symbol: null, dependencies: ["stock-tokens"],
    summary: "RWA distributor: a pool tax buys a basket of Stock Tokens for holders.",
    addresses: [ { label: "Token", address: "not-verified", role: "token" } ],
    missing: ["Official site or account not yet located", "Token and basket-holding contract addresses unknown", "Who sets the tax and controls the basket", "Lifecycle stage not independently verified"] },
  arrow: { symbol: null, dependencies: [],
    summary: "Native CDP and DeFi gateway on Robinhood Chain; launchpad live, CDP audit in flight per the seed table.",
    addresses: [ { label: "Launchpad", address: "not-verified", role: "factory" }, { label: "CDP core", address: "not-verified", role: "vault" } ],
    missing: ["Contract addresses not yet located", "CDP collateral types, oracle and liquidation path", "Audit report and covered commit", "Admin powers over the launchpad"] },
  bankr: { symbol: null, dependencies: [],
    summary: "Agent trading surface expanded onto Robinhood Chain.",
    addresses: [],
    missing: ["Official site or account not yet located", "Whether any on-chain contracts are Bankr-specific or it routes through others", "Key custody model for agent execution", "Lifecycle stage not independently verified"] },
  meridian: { symbol: null, dependencies: [],
    summary: "Native prediction-market launch partner on Robinhood Chain.",
    addresses: [],
    missing: ["Official site or account not yet located", "No deployment evidence reviewed — lifecycle recorded as announced", "Resolution and oracle design", "Collateral custody"] },
  "statics-protocol": { symbol: "STATICS", dependencies: [],
    summary: "Native protocol for redeemable multi-asset baskets, connected pools and self-backed credit; Genesis system reported live on Robinhood mainnet 2026-08-27.",
    addresses: [ { label: "Genesis system", address: "not-verified", role: "other" } ],
    missing: ["Mainnet addresses (docs reference a testnet deployment page)", "Deployed governance and timelock configuration vs the documented seven-day target", "Independent audit evidence", "Upgrade authority"] },
  safehood: { symbol: null, dependencies: ["uniswap"],
    summary: "Robinhood Chain launchpad that creates Uniswap v3 pools and opens trading directly on mainnet.",
    addresses: [ { label: "Launchpad", address: "not-verified", role: "factory" } ],
    missing: ["Mainnet addresses from the repository not yet reproduced on Blockscout", "Single platform admin wallet claim — confirm scope of powers", "Independent audit evidence", "Whether the deployer retains token-level privileges"] },
  "robinhood-index-vaults": { symbol: "rIDX", dependencies: ["stock-tokens"],
    summary: "Experimental ERC-4626 index vault for baskets of Robinhood Stock Tokens; testnet only, mock swap router.",
    addresses: [ { label: "Vault (testnet)", address: "not-verified", role: "vault" } ],
    missing: ["Testnet addresses", "Confirm no production deposit path exists", "Audit — roadmap item, none reviewed", "Mainnet plan and controls"] },
  vimen: { symbol: null, dependencies: ["stock-tokens"],
    summary: "Immutable in-kind index baskets for Robinhood Stock Tokens with per-basket deposit caps and no claimed admin keys over funds.",
    addresses: [ { label: "Basket custody", address: "not-verified", role: "vault" } ],
    missing: ["Deployed addresses and bytecode vs repository", "Immutability / no-admin-key claim not reproduced", "Basket caps and redemption path", "Independent audit evidence"] },
};
