// Facts per slug that are not in census.yaml: symbol, one-sentence summary, dependency cards, and the
// missing-evidence checklist (PRD §5.3). Known deployments come from scripts/harvest-data.mjs so the
// address list lives in one place; every one is verified:false until reproduced on Blockscout.
// Voice: PRD §7.3 — no verdicts, "an independent audit was not found in this review", "the admin
// address can …". Numbers from social posts are what an account posted, dated.
import { HARVEST } from "./harvest-data.mjs";

export const RESEARCHER = "harsharn10";
export const LINK_KIND_TO_SOURCE_KIND = { site: "official-site", app: "official-site", docs: "docs", whitepaper: "whitepaper", x: "social", github: "repository", telegram: "social", discord: "social", other: "other" };

const AUDIT = "An independent audit was not found in this review";
const LIFECYCLE_UNKNOWN = "Lifecycle not verified — no deployment evidence reviewed";

const FACTS = {
  // ---------------------------------------------------------------- PRD seed set
  pons: { symbol: "PONS", dependencies: ["uniswap", "usdg", "stock-tokens"],
    summary: "Native launchpad on Robinhood Chain: tokens launch on a V2 bonding curve and graduate to Uniswap v4; quote assets include ETH, USDG and Stock Tokens.",
    missing: ["Curve, factory and graduation-router deployment map not yet reproduced on Blockscout (the workbook names one active factory; it says several versions exist)", "Privileged roles over the curve and graduation path unknown", AUDIT, "Team identity and repository not yet located"] },
  mancer: { symbol: "MANCER", dependencies: ["uniswap"],
    summary: "Native DEX aggregator with resting orders, in a gated beta for Chain Mancers and StonkBrokers holders; the project says its router and order contracts are under audit; a Shield product is announced.",
    missing: ["Router address not yet located; the $MANCER token address comes from the workbook and is not reproduced", "Non-custodial order claim not verified against contracts", "NFT fee-claim mechanics unverified", "Audit announced 2026-08-25 — no report found in this review", "Shield: announced only — no deployment evidence reviewed"] },
  "artificial-inu": { symbol: "AI", dependencies: ["stock-tokens", "uniswap"],
    summary: "Flagship LONG launch: $AI paired to tokenized NVDA on Uniswap, with a community vault the project says accumulates NVDA from trading fees.",
    missing: ["Token address from PRD Appendix A not yet reproduced on Blockscout", "Community vault contract and its controller unknown", "Fee routing and pair mechanics unverified", "Vault NVDA balance (about $1.7M per the project) not reproduced on chain"] },
  longshot: { symbol: null, dependencies: ["hyperliquid"],
    summary: "Launch and fee-routing protocol on Robinhood Chain; fees split into a fixed Hyperliquid perp position, holder rewards and the protocol.",
    missing: ["Token address from PRD Appendix A not yet reproduced on Blockscout", "Who controls the Hyperliquid position and how funds cross venues", "Fee-split contract and admin powers unknown", AUDIT, "Multi-chain footprint (Base, Solana, BNB, HyperEVM per the workbook) not reviewed"] },
  long: { symbol: null, dependencies: ["stock-tokens", "uniswap"],
    summary: "Stock-paired launchpad (Factory + Airlock) that made stock-paired tokens possible on Robinhood Chain; $AI launched here.",
    missing: ["Full factory addresses (PRD Appendix A is truncated; the workbook points at a Dune dashboard)", "Airlock controls and who can release", "Launch fee flows", AUDIT] },
  stonkbroker: { symbol: "STONKBROKER", dependencies: ["stock-tokens", "uniswap"],
    summary: "4,444 ERC-6551 token-bound NFTs whose wallets hold Stock Tokens, with a $STONKBROKER activation token, an Anvil AMM and an announced STORMM options overlay on Uniswap v4.",
    missing: ["Collection, registry and Anvil addresses not located; the token address comes from the workbook and is not reproduced", "Who can move assets out of a token-bound account", "Activation and reward-weight mechanics unverified", "STORMM and the Leverage Machine are announced for September 2026 — no deployment evidence reviewed", "DefiLlama parent versus launchpad TVL split unexplained"] },
  index: { symbol: "INDEX", dependencies: ["stock-tokens", "uniswap", "rialto"],
    summary: "RWA distributor: a 3% tax on $INDEX trades buys Stock Tokens and distributes them to holders on a short cadence, per the project.",
    missing: ["Token address from the dossier and workbook not yet reproduced on Blockscout", "Distributor and hook contract addresses unknown", "Who sets the tax and controls the basket", "Distribution totals (about $1M per the project) not reproduced on chain"] },
  arrow: { symbol: "ARROW", dependencies: ["stock-tokens", "usdg"],
    summary: "Native CDP minting aUSD against Stock Tokens, ETFs, WETH and USDG, dated by the project to open 2026-08-31 09:30 ET after a Sherlock review; an ArrowPad launchpad shares the brand.",
    missing: ["Whether the CDP opened on 2026-08-31 — not confirmed in this review", "CDP core and stability-pool addresses not located", "Sherlock report and covered commit not reviewed", "Admin powers over caps, listings and the US-hours collateral switch", "ArrowPad factory controls"] },
  bankr: { symbol: null, dependencies: ["stock-tokens"],
    summary: "Agent execution surface on Robinhood Chain that launches tokens from X and runs its own stock-paired factory; the tokens it launches are graduations, not subjects.",
    missing: ["Factory address not located in either intake", "Key custody model for agent execution", "Launch fee flows (a 0.665% creator fee is cited by the dossier)", "Official site not located"] },
  meridian: { symbol: null, dependencies: [],
    summary: "Native perps and a prediction market under one handle; DefiLlama lists Meridian Perps and Meridian Predict TVL on Robinhood Chain.",
    missing: ["Lifecycle set from the DefiLlama listing — no deployment or official post reviewed", "Official site not located", "Resolution and oracle design", "Collateral custody and settlement asset (the workbook says USDe)"] },
  "statics-protocol": { symbol: "STATICS", dependencies: ["uniswap"],
    summary: "Native protocol for redeemable multi-asset baskets, an Operator NFT reserve and self-backed credit; Genesis epoch live on mainnet per the project, with the hooks DEX and credit not yet enabled.",
    missing: ["Mainnet addresses beyond the token (docs reference a testnet deployment page)", "Deployed governance and timelock configuration vs the documented seven-day target", AUDIT, "Upgrade authority", "USDstx is a design, not a deployment"] },
  safehood: { symbol: null, dependencies: ["uniswap"],
    summary: "Robinhood Chain launchpad that creates Uniswap v3 pools with no bonding curve; the official account has been quiet since 2026-07-16.",
    missing: [LIFECYCLE_UNKNOWN, "Mainnet addresses from the repository not yet reproduced on Blockscout", "Single platform admin wallet claim — confirm scope of powers", AUDIT, "Whether the factory rebuilt on 2026-07-15 is the one in the repository"] },
  "robinhood-index-vaults": { symbol: "rIDX", dependencies: ["stock-tokens"],
    summary: "Experimental ERC-4626 index vault for baskets of Robinhood Stock Tokens; testnet only, mock swap router.",
    missing: ["Testnet addresses", "Confirm no production deposit path exists", "Audit — roadmap item, none reviewed", "Mainnet plan and controls"] },
  vimen: { symbol: null, dependencies: ["stock-tokens"],
    summary: "Immutable in-kind index baskets for Robinhood Stock Tokens with per-basket deposit caps and no claimed admin keys over funds.",
    missing: ["Deployed addresses and bytecode vs repository", "Immutability / no-admin-key claim not reproduced", "Basket caps and redemption path", AUDIT, "Basket composition (MAG7, AI6, HOOD6 per the workbook) not reproduced"] },

  // ---------------------------------------------------------------- Grok desk subjects (2026-08-31)
  up: { symbol: "UP", dependencies: [],
    summary: "Native AMM on Robinhood Chain with a (3,3)-style emissions and buyback design; DefiLlama lists up v2 and v3 TVL and volume.",
    missing: ["Factory, router and token addresses not located", "Emissions controller and buyback executor unknown", "Whether the AMM is a fork and of what", AUDIT] },
  fables: { symbol: "PROLOGUE", dependencies: ["uniswap", "stock-tokens", "usdg"],
    summary: "ve(3,3) DEX built on Uniswap v4 hooks for stock-token pairs (NVDA/USDG, SPY/USDG, GLD/USDG) with dynamic fees and a $PROLOGUE token.",
    missing: ["PROLOGUE address from the account bio not reproduced on Blockscout", "Hook and gauge addresses unknown", "ve escrow and emissions controls", AUDIT, "Official site not located in the intake"] },
  denar: { symbol: "DENAR", dependencies: ["chainlink", "stock-tokens", "usdg"],
    summary: "Isolated money market for tokenized equities on Robinhood Chain, priced by Chainlink: lend USD or borrow against Stock Tokens; live since 2026-08-30 per the project.",
    missing: ["Token address from the project's post not reproduced on Blockscout", "Market contracts not located", "Who controls per-vault caps and the timelock", AUDIT, "dUSD not live", "Site URL not in the intake"] },
  longbow: { symbol: "BOW", dependencies: ["morpho", "usdg", "stock-tokens", "chainlink", "uniswap"],
    summary: "Credit overlay on Morpho Blue: isolated markets to borrow USDG against Stock Tokens, PONS and other collateral, with a $BOW token that shares protocol revenue per the project.",
    missing: ["BOW address not reproduced on Blockscout", "Morpho market ids and oracle contracts unknown", "Fee-split enforcement not verified against contracts", AUDIT, "TVL figures ($100k per the project on 2026-08-30; $58.6k per a third party on 2026-08-29) not reproduced"] },
  noxa: { symbol: null, dependencies: ["uniswap"],
    summary: "Launchpad that launches tokens straight into Uniswap v3 pools; the venue behind the chain's first-week memes, listed on DefiLlama with TVL and fees.",
    missing: ["Factory address not located", "Launch fee flows and who controls the factory", AUDIT] },
  virtuals: { symbol: "VIRTUAL", dependencies: [],
    summary: "Multi-chain AI-agent launch layer with a Robinhood Chain instance; DefiLlama lists its revenue on this chain. Filed as the layer — individual agents are graduations.",
    missing: ["Robinhood Chain instance contract addresses not located", "Bridged versus native token instance", "Agent launch fee mechanics on this chain", "Which entity controls the Robinhood Chain deployment"] },
  netnet: { symbol: "NET", dependencies: ["stock-tokens"],
    summary: "Reserve token whose treasury the project says holds AAPL, NVDA and SPCX Stock Tokens; DefiLlama has it under Reserve Currency at zero TVL.",
    missing: ["NET token and treasury addresses not located", "Treasury holdings (about $7.5M per the project) not reproduced", "Redemption mechanism, if any", "Official site not located"] },
  tickeryard: { symbol: null, dependencies: [],
    summary: "Synthetic-asset product shipping yBTC (WBTC routed from Arbitrum) on Robinhood Chain; incubated in the StonkBrokers stack with a $YARD token per the workbook.",
    missing: ["yBTC and YARD addresses not located", "Bridge and custody path for the BTC backing", "Mint and redeem controls", AUDIT] },
  "earn-protocol": { symbol: "EARN", dependencies: ["uniswap", "rialto", "stock-tokens", "usdg"],
    summary: "Yield layer for tokenized stocks: Uniswap v4 strategy vaults on NVDA/USDG and GME/USDG, permissionless omnipools with zaps routed through Rialto, and a $EARN token that receives buybacks.",
    missing: ["Token address from the bio and workbook not reproduced on Blockscout", "Vault and omnipool addresses unknown", "Strategy control and rebalancing powers", "Protocol fee take (10% of omnipool swap fees per the workbook) not verified against contracts", AUDIT] },
  l4va: { symbol: "L4VA", dependencies: ["stock-tokens"],
    summary: "Vault factory that issues tokens backed by locked RWAs, stocks, NFTs or memes; TGE announced for 2026-08-18 on Robinhood Chain.",
    missing: [LIFECYCLE_UNKNOWN, "Token and vault factory addresses not located", "Whether any vault holds a Stock Token", AUDIT, "Vesting for the 20% team allocation"] },
  delta: { symbol: "DELTA", dependencies: ["uniswap"],
    summary: "LP manager that calls itself the liquidity layer of Robinhood: users provide liquidity and claim fees, with a $DELTA token.",
    missing: ["Token address from the bio not reproduced on Blockscout", "Vault and manager contracts not located", "Withdrawal and rebalance powers", "TVL claim ($1M+) versus DefiLlama ($16k) unresolved", AUDIT, "Official site not located"] },
  snuggle: { symbol: null, dependencies: ["uniswap"],
    summary: "Liquidity position manager on Robinhood Chain listed by DefiLlama with TVL and daily revenue; quiet on X during the desk's pass.",
    missing: ["Contract addresses not located", "Rebalance and withdrawal powers", AUDIT, "Official site not located"] },
  sherwood: { symbol: null, dependencies: [],
    summary: "Private-transfer tool on Robinhood Chain per the desk's map, with a DefiLlama TVL row; the workbook described it as an agent capital layer with a $WOOD token.",
    missing: ["Contract addresses not located", "Freeze and upgrade powers over the pool", "Product classification unresolved between the two intakes", "Official site not located"] },
  squeeze: { symbol: null, dependencies: ["uniswap"],
    summary: "Short-interest tape reading Uniswap v3 TWAPs, live per the project, with a planned short desk that has no deployed contracts.",
    missing: ["Lifecycle announced: the project states no Desk contracts exist", "Tape data source and hosting", "Lender custody design once the Desk exists", "Liquidation on thin books — described by the project as unsolved"] },
  "agent-name-service": { symbol: null, dependencies: [],
    summary: "Name registry for agents (.agent) on Robinhood Chain with a claimed yearly fee.",
    missing: [LIFECYCLE_UNKNOWN, "Registrar contract not located", "Fee custody and revocation powers", "Official site not located"] },
  hookr: { symbol: "HOOKR", dependencies: ["uniswap"],
    summary: "Uniswap v4 hook launchpad and hook marketplace: launch a token whose pool rules (anti-snipe, surge fee, auto-burn) are the product.",
    missing: ["Token, launchpad and hook addresses from the site and GitHub not reproduced on Blockscout", "Who can upgrade a deployed hook", "Fee split into Hook Blocks not verified against contracts", AUDIT, "Hook Tokens not yet issued per the builder"] },
  "what-the-hook": { symbol: "WTH", dependencies: ["uniswap"],
    summary: "MEV redistribution inside a Uniswap v4 hook that pays traders and LPs, with a WTH token.",
    missing: ["Hook and token addresses not located", "Upgrade and redirect powers over the hook", "How MEV is captured and paid out", AUDIT, "Official site not located"] },
  quotrons: { symbol: "QUOTRON", dependencies: ["uniswap", "stock-tokens"],
    summary: "4,444 ERC-404 terminals: burning the liquid token hardwires an NFT that earns one of ten Stock Tokens from a 3% pool fee.",
    missing: ["Token, router and hook addresses from project docs not reproduced on Blockscout", "Signers of the recovery Safe and scope of the blacklist guardian", "Reward epoch status on Robinhood Chain", "V1 exploit postmortem not reviewed", "Whether the Desktop drop shares the same control plane"] },
  "pools-trade": { symbol: null, dependencies: ["uniswap"],
    summary: "Uniswap Labs launchpad minting tokens straight into Uniswap pools on Robinhood Chain.",
    missing: ["Factory address not located", "Launch fee flows", "Whether Uniswap Labs retains control of the factory", "Site URL not in the intake", "Relation to the 'Poolsfun' Sushi-V3 launches unresolved"] },
  wire: { symbol: "WIRE", dependencies: [],
    summary: "Command layer that launches tokens on Pons and executes trades from X, Telegram or web, with a $WIRE token.",
    missing: ["Token address from the bio not reproduced on Blockscout", "Key custody for user commands", "Protocol fee custody", "Details of the 2026-08-30 router-approval patch", AUDIT] },
  maxfi: { symbol: null, dependencies: ["uniswap", "stock-tokens", "usdg"],
    summary: "Managed LP positions on Stock Token / USDG pairs with no-swap rebalancing, time-delayed depeg protection and a circuit breaker in progress; no token found.",
    missing: ["Manager contract addresses not located", "Withdrawal and rebalance powers", "TVL ($8M per the bio) and payouts not reproduced", AUDIT] },
  sight: { symbol: null, dependencies: [],
    summary: "Prediction market announced for Robinhood Chain; the project states it has no token and plans a Genesis NFT mint on 2026-09-02.",
    missing: ["No market contract reviewed — lifecycle announced", "Resolution design", "Collateral custody", "Official site not located"] },
  mesh: { symbol: "MESH", dependencies: ["usdg"],
    summary: "Machine-payments gateway (MPP) on Robinhood Chain with a MESH token; USDG fee epochs are paid to large holders and Pons is listed as a merchant.",
    missing: ["Token and gateway addresses not reproduced on Blockscout", "Fee custody between epochs", "Who triggers and sizes epoch payouts", "Official site not located"] },
  foxpad: { symbol: null, dependencies: ["uniswap"],
    summary: "Launchpad attached to the FOX mascot token: pad fees split 50/50 between operations and a FOX vault, and graduated tokens auto-burn token-side Uniswap fees, per the project.",
    missing: ["Pad contract addresses not located", "Fee custody and FOX vault control", "The pad's own X handle (the linked account is the FOX token's)", AUDIT] },
  scopl: { symbol: "SCOPL", dependencies: ["uniswap"],
    summary: "Non-custodial one-tick limit orders on Uniswap V3 and V4 (the position NFT stays in the user's wallet) with fee revenue split to referrals, buybacks and operations; V2 audited by SpyWolf per the project.",
    missing: ["Token address from the bio not reproduced on Blockscout", "Nine V2 contract addresses not published", "Buyback vault and fee router control", "Whether V2 is live: the audit text and the official account disagree"] },
  website: { symbol: "WEBSITE", dependencies: [],
    summary: "Tokenized ad slots on Robinhood Chain that pay ETH to slot owners; v2 live since 2026-08-11 per the project.",
    missing: ["Slot contract and token addresses not located", "Payout routing and who controls it", "Official site not located", AUDIT] },
  lemon: { symbol: null, dependencies: ["hyperliquid"],
    summary: "Launch and trading pad on Robinhood Chain whose coins get an X account posting on-chain facts; Hyperliquid tools claimed through a Lemon terminal.",
    missing: ["Contract addresses not located", "Launch custody and fee flows", "Key custody for the Hyperliquid leg", "Official site not located", AUDIT] },
  robindex: { symbol: "ROBINDEX", dependencies: [],
    summary: "Token scanner and Telegram bot for Robinhood Chain (robindex.pro) with a $ROBINDEX token; not a stock index and not Robinhood Index Vaults.",
    missing: ["Token address from the About page not reproduced on Blockscout", "Token utility and treasury", "Three other products share the name"] },
  vynex: { symbol: "VYNEX", dependencies: ["morpho", "stock-tokens", "usdg"],
    summary: "Liquid vault shares plus a Morpho Blue NVDA/USDG borrow market (38.5% LTV) using a 30-minute TWAP oracle the project built.",
    missing: ["Token address comes from a third-party citation only", "Vault and oracle addresses not located", "Oracle control and Morpho market id", AUDIT, "Official site not located"] },
  sinjoh: { symbol: "INJOH", dependencies: ["stock-tokens"],
    summary: "Fee router: launch and creator fees are bought back into PONS and NVDA airdrops and INJOH burns per the project; Yield Banks and raffle products are announced.",
    missing: ["Token address from the bio not reproduced on Blockscout", "Router contract not located", "Who sets the fee split", AUDIT] },
  hoodlock: { symbol: "LOCK", dependencies: [],
    summary: "Native liquidity locker with a $LOCK token; 25% of Mintera.art revenue buys LOCK per the project, and a fee-split launchpad is announced.",
    missing: ["Token address from the bio not reproduced on Blockscout", "Locker contract not located", "Unlock and admin powers over locked positions", "Value locked (3M+ per the project) not reproduced", AUDIT] },
  arrows: { symbol: "ARROWS", dependencies: ["stock-tokens"],
    summary: "Fully collateralized options on tokenized stocks as transferable ERC-1155s with writer vaults earning premiums; live at small size since late August per the project.",
    missing: ["Token address from the workbook and desk not reproduced on Blockscout", "Option and writer-vault contracts not located", "Settlement and collateral controls", AUDIT] },
  hoodfun: { symbol: null, dependencies: ["uniswap"],
    summary: "Announced fair-launch pad: one transaction into a bonding curve that locks into Uniswap v3 at goal, with no presale or team allocation per the project.",
    missing: ["No deployment reviewed — last official post 2026-07-31", "Curve contract and graduation path", "Official site not located"] },
  "stonks-fun": { symbol: "STONKS", dependencies: [],
    summary: "DN-404 launchpad on Doppler whose fees burn the $STONKS platform token; a rebrand toward RWA baskets is announced.",
    missing: ["Factory and token addresses not located", "Fee burn path not verified against contracts", AUDIT, "Official site not located"] },
  swaphood: { symbol: "HOOD", dependencies: [],
    summary: "Native AMM (a PancakeSwap V3 fork per the explorer contract name) with HOOD emissions to LPs, fees to HOOD buybacks and buybacks into h33 backing.",
    missing: ["Addresses reported by the desk not reproduced here", "Emissions controller and buyback executor", AUDIT, "Docs URL (referenced as a gitbook without a link)"] },
};

/** SEED[slug] = { symbol, dependencies, summary, deployments, missing } — deployments derived from HARVEST. */
export const SEED = Object.fromEntries(Object.entries(FACTS).map(([slug, f]) => [slug, {
  ...f,
  deployments: (HARVEST[slug]?.deployments ?? []).map(({ label, address, role, chain }) => ({ label, chain: chain ?? "robinhood-chain", address, role })),
}]));
